### ISSUE TITLE
Probable cause of no re-renders on the FlatList

### ISSUE THREAD

**Issue by jakallergis** [shrivastavasamarth22/safebuy_partner#1]
In the FlatList [here](https://github.com/shrivastavasamarth22/safebuy_partner/blob/67778a57d79e06725ed8c815bc97c61d17547195/screens/InventoryFlow/AddToStockScreen.js#L111) you're checking a property in order to set the data.

Can you try and see if adding the `extraData` prop of the FlatList component with the `active` value changes anything?

I'm 99% sure that your problem is that something outside the FlatList's `data` prop is changing so now you just need to put it in the `extraData` just to let the FlatList know that you want it to re-render when that property changes too (otherwise dueto extensive perf optimisation the FlatList tries as much as possible to not re-render unless the items change references etc so it doesn't know that you need it to re-render based on another property outside the items)

Try this first:

```tsx
<FlatList
    data={active === "vegetable" ? formatData(vegetables) : formatData(fruits)}
    extraData={active}
// ...
/>
```

then if that doesn't work try this: _(basically the same just the extraData being an array)_

```tsx
<FlatList
    data={active === "vegetable" ? formatData(vegetables) : formatData(fruits)}
    extraData={[acctive]}
// ...
/>
```

and if this doesn't work either then I'm 99% sure that you just need to find which property/ies you need to track via the `extraData` prop

**Comment by shrivastavasamarth22** [comment]
Sure I'll work this out right now! Thanks for the help again

**Comment by shrivastavasamarth22** [comment]
It still doesn't working, I'll get on to researching right away!

**Comment by shrivastavasamarth22** [comment]
Solved the problem by copying the app level state to local component level state

**Comment by jakallergis** [comment]
That's not really a solution though. If your component isn't re-rendering properly through your global state, while the problem seems solved by changing to a local state, it also means that there's something wrong in your global state. Either in the way it is read by the component or in the way it is passed through to the component.
Remember, a state in React should behave the same whether it is local or global.

I would insist in making the component work with the global state. Maybe not now if your time is limited - but definitely have a look at that cause I smell something bad in the global state that might come back to bite you later in your users' runtime
